global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets: ["chess-server:5000"]

  - job_name: "docker"
    static_configs:
      - targets: ["host.docker.internal:9323"]

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alerts.yml"
