apiVersion: 1
datasources:
  - name: AWS CloudWatch
    type: cloudwatch
    access: proxy
    jsonData:
      defaultRegion: us-east-1
      authType: keys
      assumeRoleArn: arn:aws:iam::123456789012:role/GrafanaCloudWatchAccess
      logQueryFields: true

