name: Déploiement Alerting WAF

on:
  workflow_run:
    workflows: ["CI/CD Dispatcher"]
    types:
      - completed

jobs:
  deploy_alerts:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout du repo
        uses: actions/checkout@v3

      - name: 📦 Installer Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.4.0'

      - name: 🚀 Déployer Terraform
        run: |
          cd infra/chess-server/terraform
          terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: 📊 Vérification des alertes Grafana
        run: bash scripts/test_alerts.sh
