name: Déploiement Grafana

on:
  workflow_run:
    workflows: ["CI/CD Dispatcher"]
    types:
      - completed

jobs:
  deploy_grafana:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout du repo
        uses: actions/checkout@v3

      - name: 📦 Installer Docker
        run: sudo apt-get install -y docker-compose

      - name: 🚀 Déployer Grafana
        run: |
          cd infra/chess-server/monitoring
          docker-compose -f docker-compose.grafana.yml up -d

      - name: 📊 Vérifier les logs Grafana
        run: bash scripts/test_grafana.sh
